# Generated by Django 2.0.6 on 2018-07-31 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trafficnow',
            fields=[
                ('date', models.DateTimeField(blank=True, primary_key=True, serialize=False)),
                ('bin', models.TextField(blank=True, null=True)),
                ('day', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('km', models.TextField(blank=True, null=True)),
                ('location_1', models.TextField(blank=True, null=True)),
                ('location_2', models.TextField(blank=True, null=True)),
                ('road', models.TextField(blank=True, null=True)),
                ('time', models.TextField(blank=True, null=True)),
                ('type', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'trafficnow',
                'managed': False,
            },
        ),
    ]
